version: '3'
services:
  web:
    build: .
    ports:
      - "8004:8004"
    env_file:
      - ./.env
    depends_on:
      - redis
      - mongo
      - elasticsearch
    links:
      - redis
      - mongo
      - elasticsearch
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch
    networks:
        docker-elk:
networks:
  docker-elk:
    driver: bridge