version: 2.1
jobs:
  build:
    working_directory: ~/derby-app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - run: echo "this is the test job"
workflows:
  build-and-deploy:
    jobs:
      - build